title:              Ayushman Devrj
email:              ayushman@gauhati.ac.in
description:        Personal Homepage
author:             Ayushman Devraj
baseurl:            "/adevraj11"
url:                "https://adevraj11.github.io"

# Social Profiles
twitter_username:   ayushmandevraj
github_username:    BlackrockDigital
facebook_username:  ayushmandevraj

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
