title:              ayushmandevraj.in
email:              ayushman@gauhati.ac.in
description:        Personal Homepage
author:             Ayushman Devraj
baseurl:            "/"
url:                "https://ayushmandevraj.in"

# Social Profiles
twitter_username:   ayushmandevraj
github_username:    adevraj11
facebook_username:  ayushmandevraj
instagram_username: ayushmandevraj

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
